// @generated by rafka-codegen. DO NOT EDIT.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ApiVersionsRequest {
    pub client_software_name: Option<String>,
    pub client_software_version: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ApiVersionsResponse {
    pub error_code: i16,
    pub api_keys: Vec<ApiVersionsResponseApiVersion>,
    pub throttle_time_ms: Option<i32>,
    pub supported_features: Option<Vec<ApiVersionsResponseSupportedFeatureKey>>,
    pub finalized_features_epoch: Option<i64>,
    pub finalized_features: Option<Vec<ApiVersionsResponseFinalizedFeatureKey>>,
    pub zk_migration_ready: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ApiVersionsResponseApiVersion {
    pub api_key: i16,
    pub min_version: i16,
    pub max_version: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ApiVersionsResponseSupportedFeatureKey {
    pub name: String,
    pub min_version: i16,
    pub max_version: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ApiVersionsResponseFinalizedFeatureKey {
    pub name: String,
    pub max_version_level: i16,
    pub min_version_level: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ProduceRequest {
    pub transactional_id: Option<String>,
    pub acks: i16,
    pub timeout_ms: i32,
    pub topic_data: Vec<ProduceRequestTopicProduceData>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ProduceRequestTopicProduceData {
    pub name: Option<String>,
    pub topic_id: Option<[u8; 16]>,
    pub partition_data: Vec<ProduceRequestPartitionProduceData>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct ProduceRequestPartitionProduceData {
    pub index: i32,
    pub records: Option<Vec<u8>>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetCommitRequest {
    pub group_id: String,
    pub generation_id_or_member_epoch: i32,
    pub member_id: String,
    pub group_instance_id: Option<String>,
    pub retention_time_ms: Option<i64>,
    pub topics: Vec<OffsetCommitRequestOffsetCommitRequestTopic>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetCommitRequestOffsetCommitRequestTopic {
    pub name: Option<String>,
    pub topic_id: Option<[u8; 16]>,
    pub partitions: Vec<OffsetCommitRequestOffsetCommitRequestPartition>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetCommitRequestOffsetCommitRequestPartition {
    pub partition_index: i32,
    pub committed_offset: i64,
    pub committed_leader_epoch: Option<i32>,
    pub committed_metadata: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetCommitResponse {
    pub throttle_time_ms: Option<i32>,
    pub topics: Vec<OffsetCommitResponseOffsetCommitResponseTopic>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetCommitResponseOffsetCommitResponseTopic {
    pub name: Option<String>,
    pub topic_id: Option<[u8; 16]>,
    pub partitions: Vec<OffsetCommitResponseOffsetCommitResponsePartition>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetCommitResponseOffsetCommitResponsePartition {
    pub partition_index: i32,
    pub error_code: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchRequest {
    pub group_id: Option<String>,
    pub topics: Option<Vec<OffsetFetchRequestOffsetFetchRequestTopic>>,
    pub groups: Option<Vec<OffsetFetchRequestOffsetFetchRequestGroup>>,
    pub require_stable: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchRequestOffsetFetchRequestTopic {
    pub name: String,
    pub partition_indexes: Vec<i32>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchRequestOffsetFetchRequestGroup {
    pub group_id: String,
    pub member_id: Option<String>,
    pub member_epoch: Option<i32>,
    pub topics: Option<Vec<OffsetFetchRequestOffsetFetchRequestTopics>>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchRequestOffsetFetchRequestTopics {
    pub name: Option<String>,
    pub topic_id: Option<[u8; 16]>,
    pub partition_indexes: Vec<i32>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchResponse {
    pub throttle_time_ms: Option<i32>,
    pub topics: Option<Vec<OffsetFetchResponseOffsetFetchResponseTopic>>,
    pub error_code: Option<i16>,
    pub groups: Option<Vec<OffsetFetchResponseOffsetFetchResponseGroup>>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchResponseOffsetFetchResponseTopic {
    pub name: String,
    pub partitions: Vec<OffsetFetchResponseOffsetFetchResponsePartition>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchResponseOffsetFetchResponsePartition {
    pub partition_index: i32,
    pub committed_offset: i64,
    pub committed_leader_epoch: Option<i32>,
    pub metadata: Option<String>,
    pub error_code: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchResponseOffsetFetchResponseGroup {
    pub group_id: String,
    pub topics: Vec<OffsetFetchResponseOffsetFetchResponseTopics>,
    pub error_code: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchResponseOffsetFetchResponseTopics {
    pub name: Option<String>,
    pub topic_id: Option<[u8; 16]>,
    pub partitions: Vec<OffsetFetchResponseOffsetFetchResponsePartitions>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct OffsetFetchResponseOffsetFetchResponsePartitions {
    pub partition_index: i32,
    pub committed_offset: i64,
    pub committed_leader_epoch: i32,
    pub metadata: Option<String>,
    pub error_code: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct JoinGroupRequest {
    pub group_id: String,
    pub session_timeout_ms: i32,
    pub rebalance_timeout_ms: Option<i32>,
    pub member_id: String,
    pub group_instance_id: Option<String>,
    pub protocol_type: String,
    pub protocols: Vec<JoinGroupRequestJoinGroupRequestProtocol>,
    pub reason: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct JoinGroupRequestJoinGroupRequestProtocol {
    pub name: String,
    pub metadata: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct JoinGroupResponse {
    pub throttle_time_ms: Option<i32>,
    pub error_code: i16,
    pub generation_id: i32,
    pub protocol_type: Option<String>,
    pub protocol_name: Option<String>,
    pub leader: String,
    pub skip_assignment: Option<bool>,
    pub member_id: String,
    pub members: Vec<JoinGroupResponseJoinGroupResponseMember>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct JoinGroupResponseJoinGroupResponseMember {
    pub member_id: String,
    pub group_instance_id: Option<String>,
    pub metadata: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct SyncGroupRequest {
    pub group_id: String,
    pub generation_id: i32,
    pub member_id: String,
    pub group_instance_id: Option<String>,
    pub protocol_type: Option<String>,
    pub protocol_name: Option<String>,
    pub assignments: Vec<SyncGroupRequestSyncGroupRequestAssignment>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct SyncGroupRequestSyncGroupRequestAssignment {
    pub member_id: String,
    pub assignment: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct SyncGroupResponse {
    pub throttle_time_ms: Option<i32>,
    pub error_code: i16,
    pub protocol_type: Option<String>,
    pub protocol_name: Option<String>,
    pub assignment: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct HeartbeatRequest {
    pub group_id: String,
    pub generation_id: i32,
    pub member_id: String,
    pub group_instance_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct HeartbeatResponse {
    pub throttle_time_ms: Option<i32>,
    pub error_code: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct LeaveGroupRequest {
    pub group_id: String,
    pub member_id: Option<String>,
    pub members: Option<Vec<LeaveGroupRequestMemberIdentity>>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct LeaveGroupRequestMemberIdentity {
    pub member_id: String,
    pub group_instance_id: Option<String>,
    pub reason: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct LeaveGroupResponse {
    pub throttle_time_ms: Option<i32>,
    pub error_code: i16,
    pub members: Option<Vec<LeaveGroupResponseMemberResponse>>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct LeaveGroupResponseMemberResponse {
    pub member_id: String,
    pub group_instance_id: Option<String>,
    pub error_code: i16,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct SaslHandshakeRequest {
    pub mechanism: String,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct SaslHandshakeResponse {
    pub error_code: i16,
    pub mechanisms: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct SaslAuthenticateRequest {
    pub auth_bytes: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct SaslAuthenticateResponse {
    pub error_code: i16,
    pub error_message: Option<String>,
    pub auth_bytes: Vec<u8>,
    pub session_lifetime_ms: Option<i64>,
}

